In [1]:
import pandas as pd
import numpy as np

In [2]:
movies=pd.read_csv('tmdb_5000_movies.csv')
credits=pd.read_csv('tmdb_5000_credits.csv')

In [3]:
movies.shape

(4803, 20)

In [4]:
credits.head()

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                                cast  \
0  [{"cast_id": 242, "character": "Jake Sully", "...   
1  [{"cast_id": 4, "character": "Captain Jack Spa...   
2  [{"cast_id": 1, "character": "James Bond", "cr...   
3  [{"cast_id": 2, "character": "Bruce Wayne / Ba...   
4  [{"cast_id": 5, "character": "John Carter", "c...   

                                                crew  
0  [{"credit_id": "52fe48009251416c750aca23", "de...  
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...  
2  [{"credit_id": "54805967c3a36829b5002c41", "de...  
3  [{"credit_id": "52fe4781c3a36847f81398c3", "de...  
4  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...

In [5]:
movies=movies.merge(credits,on='title')

In [6]:
movies.head(1)

budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                      homepage     id  \
0  http://www.avatarmovie.com/  19995   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   

  original_title                                           overview  \
0         Avatar  In the 22nd century, a paraplegic Marine is di...   

   popularity                               production_companies  ... runtime  \
0  150.437577  [{"name": "Ingenious Film Partners", "id": 289...  ...   162.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   

                       tagline   title vote_average vote_count movie_id  \
0  Enter the World of Pandora.  Avatar          7.2      11800    19995   

                                                cast  \
0  [{"cast_id": 242, "character": "Jake Sully", "...   

                                                crew  
0  [{"credit_id": "52fe48009251416c750aca23", "de...  

[1 rows x 23 columns]

In [7]:
# Columns Needed

#genres
#homepage
#keywords
#title
#over view


In [8]:
movies=movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [9]:
movies.head()

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                            overview  \
0  In the 22nd century, a paraplegic Marine is di...   
1  Captain Barbossa, long believed to be dead, ha...   
2  A cryptic message from Bond’s past sends him o...   
3  Following the death of District Attorney Harve...   
4  John Carter is a war-weary, former military ca...   

                                              genres  \
0  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                            keywords  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...   
4  [{"id": 818, "name": "based on novel"}, {"id":...   

                                                cast  \
0  [{"cast_id": 242, "character": "Jake Sully", "...   
1  [{"cast_id": 4, "character": "Captain Jack Spa...   
2  [{"cast_id": 1, "character": "James Bond", "cr...   
3  [{"cast_id": 2, "character": "Bruce Wayne / Ba...   
4  [{"cast_id": 5, "character": "John Carter", "c...   

                                                crew  
0  [{"credit_id": "52fe48009251416c750aca23", "de...  
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...  
2  [{"credit_id": "54805967c3a36829b5002c41", "de...  
3  [{"credit_id": "52fe4781c3a36847f81398c3", "de...  
4  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...

In [10]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [11]:
movies.dropna(inplace=True)

In [12]:
movies.duplicated().sum()

0

In [13]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [14]:
import ast


def convert(obj):
    l=[]
    for i in ast.literal_eval(obj):
        l.append(i['name'])
        
    return l

In [15]:
movies['genres']=movies['genres'].apply(convert)

In [16]:
movies.head(1)

movie_id   title                                           overview  \
0     19995  Avatar  In the 22nd century, a paraplegic Marine is di...   

                                          genres  \
0  [Action, Adventure, Fantasy, Science Fiction]   

                                            keywords  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...   

                                                cast  \
0  [{"cast_id": 242, "character": "Jake Sully", "...   

                                                crew  
0  [{"credit_id": "52fe48009251416c750aca23", "de...

In [17]:
movies['keywords']=movies['keywords'].apply(convert)

In [18]:
movies.head(1)

movie_id   title                                           overview  \
0     19995  Avatar  In the 22nd century, a paraplegic Marine is di...   

                                          genres  \
0  [Action, Adventure, Fantasy, Science Fiction]   

                                            keywords  \
0  [culture clash, future, space war, space colon...   

                                                cast  \
0  [{"cast_id": 242, "character": "Jake Sully", "...   

                                                crew  
0  [{"credit_id": "52fe48009251416c750aca23", "de...

In [19]:
def convert3(obj):
    l=[]
    counter=0
    for i in ast.literal_eval(obj):
        if counter!=3:
            
            l.append(i['name'])
        else:
            break
            counter+=1
    return l

In [20]:
movies['cast']=movies['cast'].apply(convert3)

In [21]:
def fetch_director(obj):
    l=[]
    for i in ast.literal_eval(obj):
        if i['job']=='Director':
            l.append(i['name'])
            break
    return l

In [22]:
movies['crew']=movies['crew'].apply(fetch_director)

In [23]:
movies.head()

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                            overview  \
0  In the 22nd century, a paraplegic Marine is di...   
1  Captain Barbossa, long believed to be dead, ha...   
2  A cryptic message from Bond’s past sends him o...   
3  Following the death of District Attorney Harve...   
4  John Carter is a war-weary, former military ca...   

                                          genres  \
0  [Action, Adventure, Fantasy, Science Fiction]   
1                   [Adventure, Fantasy, Action]   
2                     [Action, Adventure, Crime]   
3               [Action, Crime, Drama, Thriller]   
4           [Action, Adventure, Science Fiction]   

                                            keywords  \
0  [culture clash, future, space war, space colon...   
1  [ocean, drug abuse, exotic island, east india ...   
2  [spy, based on novel, secret agent, sequel, mi...   
3  [dc comics, crime fighter, terrorist, secret i...   
4  [based on novel, mars, medallion, space travel...   

                                                cast                 crew  
0  [Sam Worthington, Zoe Saldana, Sigourney Weave...      [James Cameron]  
1  [Johnny Depp, Orlando Bloom, Keira Knightley, ...     [Gore Verbinski]  
2  [Daniel Craig, Christoph Waltz, Léa Seydoux, R...         [Sam Mendes]  
3  [Christian Bale, Michael Caine, Gary Oldman, A...  [Christopher Nolan]  
4  [Taylor Kitsch, Lynn Collins, Samantha Morton,...     [Andrew Stanton]

In [24]:
movies['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [25]:
movies['overview']=movies['overview'].apply(lambda x: x.split())

In [26]:
movies.head()

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                            overview  \
0  [In, the, 22nd, century,, a, paraplegic, Marin...   
1  [Captain, Barbossa,, long, believed, to, be, d...   
2  [A, cryptic, message, from, Bond’s, past, send...   
3  [Following, the, death, of, District, Attorney...   
4  [John, Carter, is, a, war-weary,, former, mili...   

                                          genres  \
0  [Action, Adventure, Fantasy, Science Fiction]   
1                   [Adventure, Fantasy, Action]   
2                     [Action, Adventure, Crime]   
3               [Action, Crime, Drama, Thriller]   
4           [Action, Adventure, Science Fiction]   

                                            keywords  \
0  [culture clash, future, space war, space colon...   
1  [ocean, drug abuse, exotic island, east india ...   
2  [spy, based on novel, secret agent, sequel, mi...   
3  [dc comics, crime fighter, terrorist, secret i...   
4  [based on novel, mars, medallion, space travel...   

                                                cast                 crew  
0  [Sam Worthington, Zoe Saldana, Sigourney Weave...      [James Cameron]  
1  [Johnny Depp, Orlando Bloom, Keira Knightley, ...     [Gore Verbinski]  
2  [Daniel Craig, Christoph Waltz, Léa Seydoux, R...         [Sam Mendes]  
3  [Christian Bale, Michael Caine, Gary Oldman, A...  [Christopher Nolan]  
4  [Taylor Kitsch, Lynn Collins, Samantha Morton,...     [Andrew Stanton]

In [27]:
# 'Sam Worthington'
# 'SamWorthington'

In [28]:
movies['genres']=movies['genres'].apply(lambda x: [i.replace(" ",'') for i in x])
movies['keywords']=movies['keywords'].apply(lambda x: [i.replace(" ",'') for i in x])
movies['cast']=movies['cast'].apply(lambda x: [i.replace(" ",'') for i in x])
movies['crew']=movies['crew'].apply(lambda x: [i.replace(" ",'') for i in x])

In [29]:
movies.head()

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                            overview  \
0  [In, the, 22nd, century,, a, paraplegic, Marin...   
1  [Captain, Barbossa,, long, believed, to, be, d...   
2  [A, cryptic, message, from, Bond’s, past, send...   
3  [Following, the, death, of, District, Attorney...   
4  [John, Carter, is, a, war-weary,, former, mili...   

                                         genres  \
0  [Action, Adventure, Fantasy, ScienceFiction]   
1                  [Adventure, Fantasy, Action]   
2                    [Action, Adventure, Crime]   
3              [Action, Crime, Drama, Thriller]   
4           [Action, Adventure, ScienceFiction]   

                                            keywords  \
0  [cultureclash, future, spacewar, spacecolony, ...   
1  [ocean, drugabuse, exoticisland, eastindiatrad...   
2  [spy, basedonnovel, secretagent, sequel, mi6, ...   
3  [dccomics, crimefighter, terrorist, secretiden...   
4  [basedonnovel, mars, medallion, spacetravel, p...   

                                                cast                crew  
0  [SamWorthington, ZoeSaldana, SigourneyWeaver, ...      [JamesCameron]  
1  [JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...     [GoreVerbinski]  
2  [DanielCraig, ChristophWaltz, LéaSeydoux, Ralp...         [SamMendes]  
3  [ChristianBale, MichaelCaine, GaryOldman, Anne...  [ChristopherNolan]  
4  [TaylorKitsch, LynnCollins, SamanthaMorton, Wi...     [AndrewStanton]

In [30]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [31]:
movies.head()

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                            overview  \
0  [In, the, 22nd, century,, a, paraplegic, Marin...   
1  [Captain, Barbossa,, long, believed, to, be, d...   
2  [A, cryptic, message, from, Bond’s, past, send...   
3  [Following, the, death, of, District, Attorney...   
4  [John, Carter, is, a, war-weary,, former, mili...   

                                         genres  \
0  [Action, Adventure, Fantasy, ScienceFiction]   
1                  [Adventure, Fantasy, Action]   
2                    [Action, Adventure, Crime]   
3              [Action, Crime, Drama, Thriller]   
4           [Action, Adventure, ScienceFiction]   

                                            keywords  \
0  [cultureclash, future, spacewar, spacecolony, ...   
1  [ocean, drugabuse, exoticisland, eastindiatrad...   
2  [spy, basedonnovel, secretagent, sequel, mi6, ...   
3  [dccomics, crimefighter, terrorist, secretiden...   
4  [basedonnovel, mars, medallion, spacetravel, p...   

                                                cast                crew  \
0  [SamWorthington, ZoeSaldana, SigourneyWeaver, ...      [JamesCameron]   
1  [JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...     [GoreVerbinski]   
2  [DanielCraig, ChristophWaltz, LéaSeydoux, Ralp...         [SamMendes]   
3  [ChristianBale, MichaelCaine, GaryOldman, Anne...  [ChristopherNolan]   
4  [TaylorKitsch, LynnCollins, SamanthaMorton, Wi...     [AndrewStanton]   

                                                tags  
0  [In, the, 22nd, century,, a, paraplegic, Marin...  
1  [Captain, Barbossa,, long, believed, to, be, d...  
2  [A, cryptic, message, from, Bond’s, past, send...  
3  [Following, the, death, of, District, Attorney...  
4  [John, Carter, is, a, war-weary,, former, mili...

In [32]:
new_df = movies[['movie_id','title','tags']]

In [33]:
new_df.head()

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                                tags  
0  [In, the, 22nd, century,, a, paraplegic, Marin...  
1  [Captain, Barbossa,, long, believed, to, be, d...  
2  [A, cryptic, message, from, Bond’s, past, send...  
3  [Following, the, death, of, District, Attorney...  
4  [John, Carter, is, a, war-weary,, former, mili...

In [34]:
new_df['tags']=new_df['tags'].apply(lambda x : " ".join(x))

C:\Users\Vishal Ghuge\AppData\Local\Temp\ipykernel_2804\3060717092.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x : " ".join(x))


In [35]:
new_df.head()

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                                tags  
0  In the 22nd century, a paraplegic Marine is di...  
1  Captain Barbossa, long believed to be dead, ha...  
2  A cryptic message from Bond’s past sends him o...  
3  Following the death of District Attorney Harve...  
4  John Carter is a war-weary, former military ca...

In [36]:
new_df['tags'] = new_df['tags'].str.lower()

C:\Users\Vishal Ghuge\AppData\Local\Temp\ipykernel_2804\2000485333.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].str.lower()


In [37]:
new_df.head()

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                                tags  
0  in the 22nd century, a paraplegic marine is di...  
1  captain barbossa, long believed to be dead, ha...  
2  a cryptic message from bond’s past sends him o...  
3  following the death of district attorney harve...  
4  john carter is a war-weary, former military ca...

In [38]:
from sklearn.feature_extraction.text import CountVectorizer , TfidfVectorizer

In [39]:
# countvectorizers

cv=CountVectorizer(max_features=5000,stop_words='english')
cv_vectors = cv.fit_transform(new_df['tags']).toarray()

In [40]:
cv_vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [41]:
cv_vectors[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [42]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zoo', 'zooeydeschanel', 'zoëkravitz'],
      dtype=object)

In [43]:
#  TfidfVectorizer

tf = TfidfVectorizer(max_features=5000 , stop_words='english')
tf_vectors = tf.fit_transform(new_df['tags']).toarray()

In [44]:
tf_vectors

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [45]:
tf_vectors[0]

array([0., 0., 0., ..., 0., 0., 0.])

In [46]:
tf.get_feature_names_out()

array(['000', '007', '10', ..., 'zoo', 'zooeydeschanel', 'zoëkravitz'],
      dtype=object)

In [47]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [48]:
def stem(text):
    y = []
    
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [49]:
new_df['tags'].apply(stem)

0       in the 22nd century, a parapleg marin is dispa...
1       captain barbossa, long believ to be dead, ha c...
2       a cryptic messag from bond’ past send him on a...
3       follow the death of district attorney harvey d...
4       john carter is a war-weary, former militari ca...
                              ...                        
4804    el mariachi just want to play hi guitar and ca...
4805    a newlyw couple' honeymoon is upend by the arr...
4806    "signed, sealed, delivered" introduc a dedic q...
4807    when ambiti new york attorney sam is sent to s...
4808    ever sinc the second grade when he first saw h...
Name: tags, Length: 4806, dtype: object

In [50]:
from sklearn.metrics.pairwise import cosine_similarity

# so basically here we calculate the each vectors cosine-similarity score with othes
# so here we have total 4808 records so we calculate 4808 time cosine-similarity scores 
# The similarity score of vwctor itself is one

In [51]:
cv_similarity = cosine_similarity(cv_vectors)
cv_similarity[0]

array([1.        , 0.07142857, 0.05216405, ..., 0.02326211, 0.02571722,
       0.        ])

In [52]:
sorted(list(enumerate(cv_similarity[0])), reverse=True, key=lambda x: x[1])[1:6]

[(1920, 0.23473823893078552),
 (1216, 0.23294541397390256),
 (582, 0.23097828906119441),
 (539, 0.2252817784447915),
 (507, 0.21912524504463887)]

In [53]:
tf_similarity = cosine_similarity(tf_vectors)
tf_similarity[0]

array([1.        , 0.01726282, 0.01067864, ..., 0.00518386, 0.00564531,
       0.        ])

In [54]:
sorted(list(enumerate(tf_similarity[0])), reverse=True, key=lambda x: x[1])[1:6]

[(582, 0.19817066001898234),
 (3608, 0.17818938267007922),
 (3730, 0.16589054500167955),
 (1920, 0.16164317281250615),
 (3538, 0.14844743724068635)]

In [55]:
def recommend(movie , similarity):
    movie_index = new_df[new_df['title'] == movie].index[0]
    
    distance = similarity[movie_index]
    movies_list = sorted(list(enumerate(distance)), reverse=True, key=lambda x: x[1])[1:6]
    
    for i in movies_list:
        print(new_df.iloc[i[0]].title)
    
    
    

In [56]:
new_df[new_df['title'] == 'Avatar'].index[0]

0

In [73]:
recommend(input("Enter the Movie name: ") , tf_similarity)

Enter the Movie name: Batman
Batman
Batman
Batman & Robin
Batman Returns
Batman Forever


In [58]:
recommend(input("Enter the Movie name: ") , cv_similarity)

Enter the Movie name: Batman
Batman
Batman & Robin
Batman
Batman Returns
Batman Forever


In [59]:
import pandas as pd 
from gensim.models import Word2Vec
from nltk.corpus import stopwords
from string import punctuation
from nltk.tokenize import word_tokenize

In [60]:
new_df['tags']

0       in the 22nd century, a paraplegic marine is di...
1       captain barbossa, long believed to be dead, ha...
2       a cryptic message from bond’s past sends him o...
3       following the death of district attorney harve...
4       john carter is a war-weary, former military ca...
                              ...                        
4804    el mariachi just wants to play his guitar and ...
4805    a newlywed couple's honeymoon is upended by th...
4806    "signed, sealed, delivered" introduces a dedic...
4807    when ambitious new york attorney sam is sent t...
4808    ever since the second grade when he first saw ...
Name: tags, Length: 4806, dtype: object

In [61]:
stopword_list = stopwords.words("english")
def cleaning(data):
    tokens = word_tokenize(data)
    clean_text = [word.lower() for word in tokens if(word not in punctuation) and( word.lower() not in stopword_list) and(word.isalpha())and(len(word)>2)]
    return clean_text

In [62]:
new_df['tags'] = new_df['tags'].apply(cleaning)

C:\Users\Vishal Ghuge\AppData\Local\Temp\ipykernel_2804\1625461024.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(cleaning)


In [63]:
new_df['tags']

0       [century, paraplegic, marine, dispatched, moon...
1       [captain, barbossa, long, believed, dead, come...
2       [cryptic, message, bond, past, sends, trail, u...
3       [following, death, district, attorney, harvey,...
4       [john, carter, former, military, captain, inex...
                              ...                        
4804    [mariachi, wants, play, guitar, carry, family,...
4805    [newlywed, couple, honeymoon, upended, arrival...
4806    [signed, sealed, delivered, introduces, dedica...
4807    [ambitious, new, york, attorney, sam, sent, sh...
4808    [ever, since, second, grade, first, saw, extra...
Name: tags, Length: 4806, dtype: object

In [64]:
from gensim.models import KeyedVectors
path = r"GoogleNews-vectors-negative300.bin.gz"
model = KeyedVectors.load_word2vec_format(path,binary=True)

In [65]:
len(model.word_vec('bad'))

C:\Users\Vishal Ghuge\AppData\Local\Temp\ipykernel_2804\220946776.py:1: DeprecationWarning: Call to deprecated `word_vec` (Use get_vector instead).
  len(model.word_vec('bad'))


300

In [66]:
def vectorizer(docs,model):
    feature = [] # to append vector of each review
    zero_vector = np.zeros(model.vector_size) # zero vector for handling key error
    for rew in docs : # iterate over reviews
        
        vectors = [] # append vector of each word
        
        for word in rew:
            
            
             # we are checking if word is present in model
            try :
                vectors.append(model.word_vec(word)) # get vector
            except :
                vectors.append(zero_vector)
        if vectors:
            vectors = np.asarray(vectors) #  merging all arrays into a single array
            avg_vec = vectors.mean(axis=0) # average of all vectors
            feature.append(avg_vec) # appending vector of each review
        else :
            feature.append(zero_vector) 
            
    return feature

In [67]:
final_data = new_df['tags'].to_list()

In [68]:
fetures_wv = vectorizer(final_data , model)

C:\Users\Vishal Ghuge\AppData\Local\Temp\ipykernel_2804\2837299919.py:13: DeprecationWarning: Call to deprecated `word_vec` (Use get_vector instead).
  vectors.append(model.word_vec(word)) # get vector


In [69]:
wv_vectors = fetures_wv

In [70]:
wv_similarity = cosine_similarity(wv_vectors)
wv_similarity[0]

array([1.        , 0.74793735, 0.63655024, ..., 0.62257059, 0.60010885,
       0.5613146 ])

In [71]:
wv_similarity

array([[1.        , 0.74793735, 0.63655024, ..., 0.62257059, 0.60010885,
        0.5613146 ],
       [0.74793735, 1.        , 0.64379756, ..., 0.64140063, 0.61906973,
        0.5926184 ],
       [0.63655024, 0.64379756, 1.        , ..., 0.71407417, 0.64146723,
        0.58524178],
       ...,
       [0.62257059, 0.64140063, 0.71407417, ..., 1.        , 0.69291695,
        0.64924122],
       [0.60010885, 0.61906973, 0.64146723, ..., 0.69291695, 1.        ,
        0.67516775],
       [0.5613146 , 0.5926184 , 0.58524178, ..., 0.64924122, 0.67516775,
        1.        ]])

In [74]:
recommend(input("Enter the movie name: ") , wv_similarity)

Enter the movie name: Batman
Batman
The Dark Knight Rises
The Dark Knight
Batman Begins
Batman v Superman: Dawn of Justice


In [75]:
# Custmize model

In [81]:
word_2_vec_model = Word2Vec(final_data,window=3,epochs=2,min_count=2)

In [82]:
custmize_features = vectorizer(final_data , word_2_vec_model)

In [83]:
# custmize_features
wv_custmize_vectors = custmize_features

In [84]:
wv_custmize_similarity = cosine_similarity(wv_vectors)
wv_custmize_similarity[0]

array([1.        , 0.74793735, 0.63655024, ..., 0.62257059, 0.60010885,
       0.5613146 ])

In [85]:
recommend(input("Enter the movie name: ") , wv_custmize_similarity)

Enter the movie name: Batman
Batman
The Dark Knight Rises
The Dark Knight
Batman Begins
Batman v Superman: Dawn of Justice


In [86]:
import pickle

In [98]:
with open('movies_dict.pkl','wb') as f:
    pickle.dump(dict(movies) , f)

In [96]:
movies

movie_id                                     title  \
0        19995                                    Avatar   
1          285  Pirates of the Caribbean: At World's End   
2       206647                                   Spectre   
3        49026                     The Dark Knight Rises   
4        49529                               John Carter   
...        ...                                       ...   
4804      9367                               El Mariachi   
4805     72766                                 Newlyweds   
4806    231617                 Signed, Sealed, Delivered   
4807    126186                          Shanghai Calling   
4808     25975                         My Date with Drew   

                                               overview  \
0     [In, the, 22nd, century,, a, paraplegic, Marin...   
1     [Captain, Barbossa,, long, believed, to, be, d...   
2     [A, cryptic, message, from, Bond’s, past, send...   
3     [Following, the, death, of, District, Attorney...   
4     [John, Carter, is, a, war-weary,, former, mili...   
...                                                 ...   
4804  [El, Mariachi, just, wants, to, play, his, gui...   
4805  [A, newlywed, couple's, honeymoon, is, upended...   
4806  ["Signed,, Sealed,, Delivered", introduces, a,...   
4807  [When, ambitious, New, York, attorney, Sam, is...   
4808  [Ever, since, the, second, grade, when, he, fi...   

                                            genres  \
0     [Action, Adventure, Fantasy, ScienceFiction]   
1                     [Adventure, Fantasy, Action]   
2                       [Action, Adventure, Crime]   
3                 [Action, Crime, Drama, Thriller]   
4              [Action, Adventure, ScienceFiction]   
...                                            ...   
4804                     [Action, Crime, Thriller]   
4805                             [Comedy, Romance]   
4806             [Comedy, Drama, Romance, TVMovie]   
4807                                            []   
4808                                 [Documentary]   

                                               keywords  \
0     [cultureclash, future, spacewar, spacecolony, ...   
1     [ocean, drugabuse, exoticisland, eastindiatrad...   
2     [spy, basedonnovel, secretagent, sequel, mi6, ...   
3     [dccomics, crimefighter, terrorist, secretiden...   
4     [basedonnovel, mars, medallion, spacetravel, p...   
...                                                 ...   
4804  [unitedstates–mexicobarrier, legs, arms, paper...   
4805                                                 []   
4806  [date, loveatfirstsight, narration, investigat...   
4807                                                 []   
4808           [obsession, camcorder, crush, dreamgirl]   

                                                   cast                crew  \
0     [SamWorthington, ZoeSaldana, SigourneyWeaver, ...      [JamesCameron]   
1     [JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...     [GoreVerbinski]   
2     [DanielCraig, ChristophWaltz, LéaSeydoux, Ralp...         [SamMendes]   
3     [ChristianBale, MichaelCaine, GaryOldman, Anne...  [ChristopherNolan]   
4     [TaylorKitsch, LynnCollins, SamanthaMorton, Wi...     [AndrewStanton]   
...                                                 ...                 ...   
4804  [CarlosGallardo, JaimedeHoyos, PeterMarquardt,...   [RobertRodriguez]   
4805  [EdwardBurns, KerryBishé, MarshaDietlein, Cait...       [EdwardBurns]   
4806  [EricMabius, KristinBooth, CrystalLowe, GeoffG...        [ScottSmith]   
4807  [DanielHenney, ElizaCoupe, BillPaxton, AlanRuc...        [DanielHsia]   
4808  [DrewBarrymore, BrianHerzlinger, CoreyFeldman,...   [BrianHerzlinger]   

                                                   tags  
0     [In, the, 22nd, century,, a, paraplegic, Marin...  
1     [Captain, Barbossa,, long, believed, to, be, d...  
2     [A, cryptic, message, from, Bond’s, past, send...  
3     [Following, the, death, of, Dis

In [89]:
with open ("cv_similarity.pkl","wb") as f:
    pickle.dump(cv_similarity, f)

In [90]:
with open ("tf_similarity.pkl","wb") as f:
    pickle.dump(tf_similarity, f)

In [91]:
with open ("wv_similarity.pkl","wb") as f:
    pickle.dump(wv_similarity, f)

In [92]:
with open ("wv_custmize_similarity.pkl","wb") as f:
    pickle.dump(wv_custmize_similarity, f)

In [93]:
import requests
from tqdm import tqdm


# url = "https://example.com/image.jpg"
# response = requests.get(url)
for i in tqdm(new_df['movie_id']):
    
    pass

100%|██████████████████████████████████████████████████████████████████████████| 4806/4806 [00:00<00:00, 965089.53it/s]


In [95]:
new_df

movie_id                                     title  \
0        19995                                    Avatar   
1          285  Pirates of the Caribbean: At World's End   
2       206647                                   Spectre   
3        49026                     The Dark Knight Rises   
4        49529                               John Carter   
...        ...                                       ...   
4804      9367                               El Mariachi   
4805     72766                                 Newlyweds   
4806    231617                 Signed, Sealed, Delivered   
4807    126186                          Shanghai Calling   
4808     25975                         My Date with Drew   

                                                   tags  
0     [century, paraplegic, marine, dispatched, moon...  
1     [captain, barbossa, long, believed, dead, come...  
2     [cryptic, message, bond, past, sends, trail, u...  
3     [following, death, district, attorney, harvey,...  
4     [john, carter, former, military, captain, inex...  
...                                                 ...  
4804  [mariachi, wants, play, guitar, carry, family,...  
4805  [newlywed, couple, honeymoon, upended, arrival...  
4806  [signed, sealed, delivered, introduces, dedica...  
4807  [ambitious, new, york, attorney, sam, sent, sh...  
4808  [ever, since, second, grade, first, saw, extra...  

[4806 rows x 3 columns]